### ISSUE TITLE
cache_status_header not working

### ISSUE THREAD

**Issue by MJimmyChen-reform** [long2ice/fastapi-cache#442] opened 2024-09-23 07:22 UTC
The parameter cache_status_header for the @cache decorator to change the name of the header doesn't work.
Also furthermore the status of this header always give me MISS for some reason?

**Comment by rthomas-sf** [comment] 2024-10-10 22:30
Any fix for this? The X-Fastapi-Cache header is not returned at all in my case. No way to know whether it was a cache hit or not.

**Comment by vicchi** [comment] 2024-11-09 10:52
@MJimmyChen @rthomas-sf Using a modified version of the quick start code with a custom `cache_status_header` set, I can't reproduce your issue. Can you provide a demonstrable test which shows this behaviour please?

```
#!/usr/bin/env python
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
import time

from fastapi import FastAPI
from starlette.requests import Request
from starlette.responses import Response

from fastapi_cache import FastAPICache
from fastapi_cache.backends.redis import RedisBackend
from fastapi_cache.decorator import cache

from redis import asyncio as aioredis
import uvicorn


@asynccontextmanager
async def lifespan(_: FastAPI) -> AsyncIterator[None]:
    redis = aioredis.from_url("redis://0.0.0.0")
    FastAPICache.init(RedisBackend(redis), prefix="fastapi-cache", cache_status_header="X-Custom-Cache")
    yield


app = FastAPI(lifespan=lifespan)


@cache()
async def get_cache():
    return 1


@app.get("/")
@cache(expire=10)
async def index(request: Request):
    return time.time()


if __name__ == "__main__":
    uvicorn.run(app, port=8000)
```

```
> GET http://localhost:8000/
< 200 OK
< date: Sat, 09 Nov 2024 10:50:02 GMT
< server: uvicorn
< content-length: 17
< content-type: application/json
< cache-control: max-age=10
< etag: W/7418826929730291505
< x-custom-cache: MISS
```

**Comment by MJimmyChen-reform** [comment] 2024-11-12 07:48
@vicchi Hey thanks for reaching out. It seems like the custom cache_status_header is working in my code but the status of it is still always giving me MISS instead of HIT except for when it is expiring (last second). 
For example: 
- I do the request at 09 Nov 2024 10:50:02 GMT with the result being cached for 10 seconds
- Whenever I do the same API call within the expiration period, it keeps giving **x-custom-cache-status: MISS** 
- When it is 09 Nov 2024 10:50:11 GMT, so 1 second before the cache expiration, the API call gives me **x-custom-cache-status: HIT**

Then another issue:
Whenever I invalidate that specific cache entry through API call or through Redis Insight and call the same endpoint again, it still gives me the previously invalidated cached result and doesn't cache a new result (in Redis Insight). Is this due to browser caching or due to any wrong setup?

```
REDIS_URL = "redis://localhost:6379"
redis_connection = aioredis.from_url(
    REDIS_URL, decode_responses=False, password=REDIS_PASSWORD
)

protected_router = APIRouter(
    dependencies=[Depends(get_current_user)] 
)

async def init_cache():
    redis = redis_connection
    FastAPICache.init(
        RedisBackend(redis),
        prefix="fastapi-cache",
        cache_status_header="X-Custom-Cache-Status",
    )

@asynccontextmanager
async def lifespan(_: FastAPI) -> AsyncIterator[None]:
    await init_cache()  # Initialize the cache on startup
    yield

app = FastAPI(
    title="API",
    description="The API",
    version=API_VERSION, # defined somewhere
    openapi_tags=tags_metadata, #defined somewhere
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@protected_router.get("/test123")
@cache(expire=10)
async def index(request: Request):
    return time.time()

@cache()
async def get_cache():
    return 1
```

**Comment by vicchi** [comment] 2024-11-12 08:09
@MJimmyChen It's hard to tell exactly as `protected_router` isn't shown in your code sample but are you sure you're actually using a Redis instance? Your code defines `redis_connection` as a `str` which is then assigned to a local variable in `init_cache()` which is then passed in to the `RedisBacked` constructor. 

But the signature for the constructor is for an instance of either `Redis[bytes]` or `RedisCluster[bytes]` not a Redis DSN connection string.

**Comment by MJimmyChen-reform** [comment] 2024-11-12 08:13
> @MJimmyChen It's hard to tell exactly as `protected_router` isn't shown in your code sample but are you sure you're actually using a Redis instance? Your code defines `redis_connection` as a `str` which is then assigned to a local variable in `init_cache()` which is then passed in to the `RedisBacked` constructor.
> 
> But the signature for the constructor is for an instance of either `Redis[bytes]` or `RedisCluster[bytes]` not a Redis DSN connection string.

Oh wait my mistake when copying and modifying the code over, it should be: (will also edit it in the original)
protected_router is just to secure the API endpoints w/ authentication
```
REDIS_URL = "redis://localhost:6379"
redis_connection = aioredis.from_url(
    REDIS_URL, decode_responses=False, password=REDIS_PASSWORD
)

protected_router = APIRouter(
    dependencies=[Depends(get_current_user)] 
)
```

**Comment by vicchi** [comment] 2024-11-12 08:16
@MJimmyChen Got it ... I'll take a look at this later on today and get back to you

**Comment by MJimmyChen-reform** [comment] 2024-11-12 08:23
This is my used setup:

Python: 3.12.4
fastapi-cache2: 0.2.2

docker-compose.yml:
```
services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack-name
    environment:
      - REDIS_ARGS=--requirepass password_here --appendonly yes  
    ports:
      - "6379:6379"  
      - "8001:8001"  
    volumes:
      - redis-data:/data  
    restart: unless-stopped  

volumes:
  redis-data:
    driver: local
```

**Comment by vicchi** [comment] 2024-11-12 15:15
@MJimmyChen I have a working example based on your sample code for you. Using the same `docker-compose.yml` file to spin up a Redis instance and with the following dependencies and environment (though this should also work out of the box on other OS and Python variants). I've not used `aioredis` as that is now deprecated in favour of async support in the official Redis Python package.

```
$ pip list | egrep 'redis|fastapi|uvicorn'
fastapi                   0.115.4
fastapi-cache2.    0.2.2
redis                      5.2.0
types-redis           4.6.0.20241004
uvicorn                 0.32.0

$ uname -a
Darwin garys-m1-mbp-e.vicchi.xyz 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000 arm64

$ python --version
Python 3.13.0
```
Sample code ...

```
#!/usr/bin/env python

from contextlib import asynccontextmanager
import os
import time
from typing import AsyncIterator, Dict

from fastapi import APIRouter, Depends, FastAPI, Request, Response
from fastapi.middleware.cors import CORSMiddleware
import uvicorn

import redis.asyncio as redis
from fastapi_cache import FastAPICache
from fastapi_cache.backends.redis import RedisBackend
from fastapi_cache.decorator import cache

API_VERSION = 'v1'
REDIS_URL = "redis://localhost:6379"
REDIS_PASSWORD = os.getenv('REDIS_PASSWORD')

def get_current_user() -> Dict[str, str]:
    return {
        'username': 'user',
        'email': 'user@example.com'
    }

async def init_cache() -> None:
    redis_client = await redis.from_url(
        REDIS_URL,
        decode_responses=False,
        password=REDIS_PASSWORD
    )

    FastAPICache.init(
        RedisBackend(redis_client),
        prefix="fastapi-cache",
        cache_status_header="X-Custom-Cache-Status"
    )

@asynccontextmanager
async def lifespan(_: FastAPI) -> AsyncIterator[None]:
    await init_cache()  # Initialize the cache on startup
    yield

app = FastAPI(
    title="API",
    description="The API",
    version=API_VERSION, # defined somewhere
    # openapi_tags=tags_metadata, #defined somewhere
    lifespan=lifespan,
)

protected_router = APIRouter(
    dependencies=[Depends(get_current_user)]
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@protected_router.get("/test123")
@cache(expire=10)
async def index(request: Request, response: Response) -> Dict[str, float]:
    retval = {'time': time.time()}
    return retval

app.include_router(protected_router)

if __name__ == "__main__":
    uvicorn.run("cachetest:app", log_level='debug', reload=True)
```

Run as `REDIS_PASSWORD=<password> ./cachetest.py`

```
$ http -v get http://localhost:8000/test123
GET /test123 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:8000
User-Agent: HTTPie/3.2.4

HTTP/1.1 200 OK
cache-control: max-age=10
content-length: 26
content-type: application/json
date: Tue, 12 Nov 2024 15:13:47 GMT
etag: W/426757858892756212
server: uvicorn
x-custom-cache-status: MISS

{
    "time": 1731424427.537614
}

$ http -v get http://localhost:8000/test123
GET /test123 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:8000
User-Agent: HTTPie/3.2.4

HTTP/1.1 200 OK
cache-control: max-age=8
content-length: 26
content-type: application/json
date: Tue, 12 Nov 2024 15:13:49 GMT
etag: W/426757858892756212
server: uvicorn
x-custom-cache-status: HIT

{
    "time": 1731424427.537614
}
```

**Comment by MJimmyChen-reform** [comment] 2024-11-13 08:57
@vicchi thanks for providing the example.
I decided to take a different approach and use postman to test the responses instead of the FastAPI Swagger UI (/docs) and found out that it has been working properly in usage (when called through the application using the endpoints) but not when the requests are sent by the Swagger UI. 

When I use Swagger UI to call the endpoints multiple times, it gives me the previously always MISS behaviour and clearing the cache and calling it again via the Swagger UI would not cache the result.

With using Postman it does the expected behaviour. Furthermore after using Postman to cache the result at first, the Swagger UI does generate a HIT on the cache header

**Comment by vicchi** [comment] 2024-11-13 12:16
@MJimmyChen Glad to hear you've got it all sorted; I'll close this issue now but feel free to reopen if you run into any more problems.

**Closed as completed by vicchi** 2024-11-13 12:16 UTC
Labels: invalid, question, cant-reproduce

**Comment by MJimmyChen-reform** [comment] 2024-11-13 12:19
> @MJimmyChen Glad to hear you've got it all sorted; I'll close this issue now but feel free to reopen if you run into any more problems.

Maybe we'll need to open a new issue for the Swagger UI always returning MISS issue as it might be related to https://github.com/long2ice/fastapi-cache/issues/446
